added device-name component to the dashboard and extended one-shot-de…
iotaledger/cxc-slu-authenticity pull request #124
Opened 2022-05-11 07:58 UTC by JuriBog

…vice/create endpoint with a device name paramter

2022-05-11 21:30 UTC, mastrogiovanni requested changes
Few small changes mostly related to the creation of a single point to establish channelName from the deviceName

2022-05-11 21:30 UTC, mastrogiovanni commented on dashboard/src/components/dashboard.svelte
> +					value: `channel-${device.name}` ?? '-'
In reality this information don't need to be inferred. What happens if the backend logic in giving the names will change? This information need to be provided by the backend together with the name.

2022-05-11 21:30 UTC, mastrogiovanni commented on dashboard/src/lib/index.ts
> +        const channel = await createChannel(`channel-${deviceName}`,'',[{ type: 'cxc', source: 'cxc' }]);
the logic of composition of channelName need to be in a separate method is used in more than one place.

2022-05-16 12:54 UTC, dominic22 commented on one-shot-device/src/devices/device-registration.controller.ts
> +	@Post('/create/:channelAddress/:creator/:deviceName')
the deviceName should be part of the body not path

2022-05-17 13:08 UTC, jacekroszkowiakdev approved these changes
Looks all ok to me - good job!

2022-05-17 13:13 UTC, dominic22 commented on dashboard/src/lib/index.ts
> +            const deviceResponse = await fetch(`http://localhost:3010/api/v1/one-shot-device/create/${channel?.channelAddress}/${get(authenticationData)?.did}`, {
why is there a static url?

2022-05-17 13:14 UTC, dominic22 commented on one-shot-device/src/devices/device-registration.controller.ts
> +	async createAndSubscribe(@Param('channelAddress') channelAddress: string, @Param('creator') creator: string, @Body() deviceName: { name: string }) {
maybe better to call the body `body` and not deviceName

2022-05-17 13:15 UTC, dominic22 commented on one-shot-device/src/devices/device-registration.controller.ts
> +	async createAndSubscribe(@Param('channelAddress') channelAddress: string, @Param('creator') creator: string, @Body() deviceName: { name: string }) {
is this name now mandatory or optional?

2022-05-17 13:47 UTC, dominic22 approved these changes

2022-05-17 13:59 UTC, merged