40 collector channel subscription
iotaledger/cxc-slu-authenticity pull request #48
Opened 2022-03-02 13:41 UTC by JuriBog

2022-03-03 08:08 UTC, mastrogiovanni requested changes

2022-03-09 09:25 UTC, dominic22 commented on authenticity-collector/src/channel-subscription/channel-subscription.service.ts
> +		const collector = JSON.parse(collectorJson);
This assume we store the identity with its secret keys in a plain json file. This is not very secure and we need to adjust in a follow up story.

2022-03-09 09:26 UTC, dominic22 commented on authenticity-collector/.env.example
> +API_KEY=<API_KEY>
If this is the url of the integration service please name it IS_API_KEY and IS_API_URL

2022-03-09 13:53 UTC, dominic22 approved these changes

2022-03-09 13:53 UTC, merged